---
- name: Test reachability and path to destinations
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: Ping destinations
      shell: ping -c 1 -w 2 {{ item }}
      loop: "{{ groups['targets'] }}"
      register: ping_output
      ignore_errors: yes
      no_log: traceroute
      changed_when: false
    - name: Ping report
      debug:
        msg: "{{ item.stdout.split('\n') }}"
      when: item.rc == 0
      loop: "{{ ping_output.results }}"

    - name: Traceroute to destinations
      shell: traceroute -m 10 -n {{ item }}
      loop: "{{ groups['targets'] }}"
      register: trace_output
      ignore_errors: yes
      no_log: traceroute
      changed_when: false
    - name: Traceroute report
      debug:
        msg: "{{ item.stdout.split('\n') }}"
      when: item.rc == 0
      loop: "{{ trace_output.results }}"